language: go

go:
  - "1.8"
  - "1.9"
  - "1.10"
  - "1.11"

before_install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure

before_script:
  - echo $TRAVIS_GO_VERSION

script:
  - bash ./scripts/test.sh

after_success:
  - if [[ $TRAVIS_GO_VERSION == 1.11* ]]; then bash <(curl -s https://codecov.io/bash); fi
