# This is a weird way of telling Travis to use the fast container-based test
# runner instead of the slow VM-based runner.
sudo: false

# Only clone the most recent commit.
git:
  depth: 1

language: go

go:
  - "1.8"
  - "1.9"
  - "1.10"
  - "1.11"

# Skip the install step. Don't `go get` dependencies. Only build with the code
# in vendor/. See https://docs.travis-ci.com/user/languages/go/#godep-support
install: true

# Don't email me the results of the test runs.
notifications:
  email: false


before_script:
  - echo $TRAVIS_GO_VERSION

script:
  - bash ./scripts/test.sh

after_success:
  - if [[ $TRAVIS_GO_VERSION == 1.11* ]]; then bash <(curl -s https://codecov.io/bash); fi
